### ISSUE TITLE
Create PR to parity repo for sokol and core networks

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/POAPs#17]
### Title

      Title: Additional network support in main parity client 
      Layer: Community Tools

### Abstract

Similar to `parity --chain kovan` there should be a cli way to start a `core` and `sokol` network by
submitting necessary PR to [parity github repository](https://github.com/paritytech/parity)

Example: 
```
parity --chain poacore
parity --chain poasokol
```

### Rationale

It's much easier to start POA instance node if it would be included into the parity binary

### Implementation

Spec.json files could be downloaded from 
https://github.com/poanetwork/poa-chain-spec/tree/core
https://github.com/poanetwork/poa-chain-spec/tree/sokol

as well as bootnodes.txt should be also included into the parity build

**Comment by phahulin** [comment]
Here's a branch that seems to be working: https://github.com/poanetwork/parity/tree/add-poa-chains
to compile install [dependencies required by parity](https://github.com/paritytech/parity#build-dependencies) and run `cargo build --release`, binary will be in `targer/release/` folder.

Or if you're on Ubuntu 16.04 here's [the binary](https://transfer.sh/THEIf/parity) (`sha256sum` == `589f374307968f2e5b5f6d89c34c567e75c8af34c95582b9258036155f7685dc`).

To start the chain, run
```
parity --chain poacore --base-path test-poacore
```
or
```
parity --chain poasokol --base-path test-poasokol
```
after the test remove temp folder `rm -rf test-poacore` or `rm -rf test-poasokol`

----

Few notes:
1. note that this is build from `master` branch of parity, there are some errors unrelated to these changes, but syncing works.
2. had to move list of reserved-peers to `nodes` section of [spec.json](https://github.com/poanetwork/parity/blob/f8caffc1c2373738f44d6f7823ff29a43c7a4df4/ethcore/res/ethereum/poacore.json#L106) which turns them into bootnodes. But connection to bootnodes is not that stable (this is why we use reserved-peers).
3. we'll need to submit to parity all hardforks and bootnodes updates and wait for new parity release for them to be applied

For these reasons, I think we should leave the "old" way for nodes critical to the network, when we directly use `spec.json` and `bootnodes.txt` (as reserved peers). It's more flexible.

**Comment by 5chdn** [comment]
Happy to assign this to me if desired. Having a list of boot nodes in the parity-ethereum repository, still allows you to maintain your list of reserved peers elsewhere though if this is desired.

**Comment by varasev** [comment]
Parity now supports

```
parity --chain poacore
parity --chain poasokol
parity --chain xdai
```

so I'm closing this issue.
